/**
 * deploy.test.js — the committed deployment configuration, held to the template.
 *
 * Decides: that `render.yaml` declares every variable in `.env.example` (so the deployed
 * API has every variable set), that its production values are the safe ones, that no
 * secret is committed, that the environment it describes actually boots the validator,
 * and that `netlify.toml` builds and publishes what exists.
 *
 * Does NOT decide: whether the hosts accept the files. That is checked by deploying.
 *
 * Parsing is deliberately plain — a line scan of two small files — rather than a YAML
 * dependency, because the shapes are fixed and a new dependency for a test is not.
 */

import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile, access } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { validateEnv } from '../apps/server/src/config/env.js';
import { createApp } from '../apps/server/src/http/app.js';
import { createMemoryStore } from '../apps/server/src/store/memoryStore.js';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const read = (relative) => readFile(join(repoRoot, relative), 'utf8');

/** Active assignments in .env.example (commented examples excluded), name -> value. */
async function templateVars() {
  const vars = new Map();
  for (const line of (await read('.env.example')).split('\n')) {
    const match = line.match(/^([A-Z][A-Z0-9_]*)=(.*)$/);
    if (match) vars.set(match[1], match[2].trim());
  }
  return vars;
}

/** render.yaml's envVars: name -> { value?, sync?, generateValue? }. */
async function renderVars() {
  const vars = new Map();
  let current = null;
  for (const line of (await read('render.yaml')).split('\n')) {
    const key = line.match(/^\s*- key:\s*(\S+)\s*$/);
    if (key) {
      current = {};
      vars.set(key[1], current);
      continue;
    }
    const field = line.match(/^\s+(value|sync|generateValue):\s*(.*?)\s*$/);
    if (field && current) current[field[1]] = field[2].replace(/^"(.*)"$/, '$1');
  }
  return vars;
}

/** Injected by the host, or used only by local fixtures. */
const NOT_DECLARED = new Set(['PORT', 'FIXTURE_PORT']);

/** Secrets and deployment URLs: asked for at deploy time, never committed. */
const ASKED_AT_DEPLOY = ['WEB_ORIGIN', 'MONGODB_URI', 'GEMINI_API_KEY', 'SEARCH_API_KEY'];

/** Variables whose production value is meant to differ from the local template. */
const PRODUCTION_DIFFERS = new Set([
  'NODE_ENV', 'WEB_ORIGIN', 'TRUST_PROXY_HOPS', 'MONGODB_URI', 'SESSION_SECRET',
  'GEMINI_API_KEY', 'SEARCH_API_KEY', 'ALLOW_PRIVATE_HOSTS',
]);

test('render.yaml declares every variable in .env.example', async () => {
  const template = await templateVars();
  const render = await renderVars();

  assert.ok(template.size > 20, 'the template was read');
  const missing = [...template.keys()].filter((name) => !NOT_DECLARED.has(name) && !render.has(name));
  assert.deepEqual(missing, [], 'declared in the template but not deployed');

  const unknown = [...render.keys()].filter((name) => name !== 'NODE_VERSION' && !template.has(name));
  assert.deepEqual(unknown, [], 'deployed but not documented in the template');
});

test('render.yaml carries the production-safe values and commits no secret', async () => {
  const render = await renderVars();

  assert.equal(render.get('NODE_ENV').value, 'production');
  assert.equal(render.get('ALLOW_PRIVATE_HOSTS').value, 'false', 'the SSRF guard must be on in production');
  assert.equal(render.get('TRUST_PROXY_HOPS').value, '2');
  assert.equal(render.get('SESSION_SECRET').generateValue, 'true', 'generated by the host, never committed');
  assert.equal(render.get('SESSION_SECRET').value, undefined);

  for (const name of ASKED_AT_DEPLOY) {
    assert.equal(render.get(name).sync, 'false', `${name} must be asked for at deploy time`);
    assert.equal(render.get(name).value, undefined, `${name} must not have a committed value`);
  }
});

test('render.yaml does not drift from the template on the values that should match', async () => {
  const template = await templateVars();
  const render = await renderVars();

  for (const [name, entry] of render) {
    if (!template.has(name) || PRODUCTION_DIFFERS.has(name)) continue;
    assert.equal(entry.value, template.get(name), `${name}: render.yaml says ${entry.value}, the template ${template.get(name)}`);
  }
});

test('the environment render.yaml describes passes the boot validator as production', async () => {
  const render = await renderVars();
  const env = Object.fromEntries([...render].map(([name, entry]) => [name, entry.value]));
  Object.assign(env, {
    PORT: '10000',
    WEB_ORIGIN: 'https://prep-kit.netlify.app',
    MONGODB_URI: 'mongodb+srv://user:pass@cluster0.example.mongodb.net/ai_interview_prep_kit?retryWrites=true',
    SESSION_SECRET: 'x'.repeat(44),
    GEMINI_API_KEY: 'deploy-test-key',
    SEARCH_API_KEY: '',
  });

  const result = validateEnv(env);
  assert.equal(result.ok, true, JSON.stringify(result.problems));
  assert.equal(result.config.isProduction, true);
  assert.equal(result.config.retrieval.allowPrivateHosts, false);
  assert.equal(result.config.server.trustProxyHops, 2);

  // And the one dangerous combination is still refused.
  assert.equal(validateEnv({ ...env, ALLOW_PRIVATE_HOSTS: 'true' }).ok, false);
});

test('production trusts exactly the configured number of proxies, and local trusts none', async () => {
  const base = { sessionSecret: 'x'.repeat(44), server: { webOrigin: 'https://prep-kit.netlify.app', trustProxyHops: 2 } };

  const production = createApp({ store: createMemoryStore(), config: { ...base, isProduction: true }, log: () => {} });
  assert.equal(production.get('trust proxy'), 2);

  const local = createApp({ store: createMemoryStore(), config: { ...base, isProduction: false }, log: () => {} });
  assert.equal(local.get('trust proxy'), false);
});

test('netlify.toml builds the web client from the root and publishes its dist', async () => {
  const toml = await read('netlify.toml');
  const setting = (name) => (toml.match(new RegExp(`^\\s*${name}\\s*=\\s*"([^"]*)"`, 'm')) ?? [])[1];

  const { scripts } = JSON.parse(await read('package.json'));
  const command = setting('command');
  assert.match(command, /^npm run (\S+)$/);
  assert.ok(scripts[command.split(' ').at(-1)], `root script for "${command}" exists`);

  assert.equal(setting('publish'), 'apps/web/dist');
  const web = JSON.parse(await read('apps/web/package.json'));
  assert.match(web.scripts.build, /scripts\/redirects\.js/, 'the web build writes _redirects');
  await access(join(repoRoot, 'apps/web/scripts/redirects.js'));
});

test('the local dev server loads the root .env; the production start reads only the host environment', async () => {
  const server = JSON.parse(await read('apps/server/package.json'));
  // Workspace scripts run with apps/server as the working directory.
  assert.match(server.scripts.dev, /--env-file-if-exists=\.\.\/\.\.\/\.env/);
  assert.doesNotMatch(server.scripts.start, /env-file/, 'a deployed service is configured by its host, never by a stray file');
  await access(join(repoRoot, 'apps/server', '../../.env.example'));
});

test('vercel.json proxies /api to an https API origin first, then falls back to the app', async () => {
  const { rewrites } = JSON.parse(await read('vercel.json'));
  assert.equal(rewrites.length, 2);

  const [api, fallback] = rewrites;
  assert.equal(api.source, '/api/:path*');
  const destination = new URL(api.destination.replace(':path*', 'x'));
  assert.equal(destination.protocol, 'https:');
  assert.equal(destination.pathname, '/api/x', 'the /api prefix is kept, never doubled or dropped');

  // Last, so a real /api route and the built assets are never swallowed by it; without it,
  // reloading /kits/abc on the static host is a 404.
  assert.deepEqual(fallback, { source: '/(.*)', destination: '/index.html' });
});

test('the server can be started by a host without watch mode', async () => {
  const { scripts } = JSON.parse(await read('package.json'));
  const server = JSON.parse(await read('apps/server/package.json'));
  assert.equal(server.scripts.start, 'node src/index.js');
  assert.match(scripts.start, /--workspace @aipk\/server/);
  assert.match((await read('render.yaml')), /startCommand: npm start/);
});
